# diary sample config

# Determines the name of entries
ENTRY_PATH="$(date '+%Y/%-m/%-d').md"

# Prefills new entries with some text
PREFILL="# $(date '+%A %d %B, %Y %I:%M %p')\n\n"

# Appends existing entries with some text
PREFILL_EDIT="## $(date '+%I:%M %p')"

# Opens EDITOR to begin editing immediately
USE_EDITOR=true

# Sets the editor to use with diary
EDITOR=nano

# Run a command after editing
HOOK="git add -A && git commit -m 'journaling: $(date)'"

# This is set automatically and should not be manually edited
CONFIG_VERSION=1
